# Generated by Django 2.2.12 on 2020-07-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='post',
            new_name='name',
        ),
    ]
