# Generated by Django 2.2.12 on 2020-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default='null'),
        ),
    ]
