# Generated by Django 2.2.12 on 2020-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200706_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='user',
            new_name='auther',
        ),
        migrations.AddField(
            model_name='cv',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
