# Generated by Django 2.2.12 on 2020-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='auther',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='cv',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work',
            field=models.TextField(),
        ),
    ]
