# Generated by Django 2.2.12 on 2020-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200706_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='name',
        ),
        migrations.AddField(
            model_name='cv',
            name='about',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='cv',
            name='work',
            field=models.TextField(default='null'),
        ),
    ]
