# Generated by Django 2.2.12 on 2020-07-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200728_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='author',
        ),
    ]
